### ISSUE TITLE
Licensing your code

### ISSUE THREAD

**Issue by marioa** [ulfelder/dart-throwing-chimp#2]
It's great that you make your source code available but it would even be greater if you could explicitly licence it so others know how they can legitimately use it, i.e. you are transferring aspects of your copyright.

**Comment by ulfelder** [comment]
Thank you for bringing this up. I wasn't aware that this was/is an issue, and I don't know where to start to address it, but I will give it a shot.

**Comment by ulfelder** [comment]
Okay, @marioa, I think I've got that squared away now. If you wouldn't mind taking a look at what I've done and either a) closing the issue if it looks good or b) letting me know what I ought to do differently, I would appreciate it.

**Comment by marioa** [comment]
Looks good to me. Thanks for doing this. As an aside ACLED now have an API that makes pulling data from them a lot easier, see http://www.acleddata.com/wp-content/uploads/2016/07/ACLED_API-User-Guide_28072016.pdf. Thanks for doing the licensing.

**Comment by ulfelder** [comment]
Thank you. And regarding ACLED, the acledr.R script uses the API. I'll get rid of the now-deprecated acled.importer.R to avoid confusion.
